
import { AuthProvider } from "./Providers";
import "./globals.css";
import { Inter } from "next/font/google";
import ClientOnly from "../components/ClientOnly";
import Navbar from "../components/navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "TripNest",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    
      <body className={inter.className}>
        <AuthProvider>
        <ClientOnly>
    <Navbar/>
      </ClientOnly>
          
          {children}</AuthProvider>
      </body>
    </html>
  );
}
